# me/userinfobot

[pyrogram]
api_id = 11390013                        # required
api_hash = "d1c98093308bf40c69021439e991bafc"                       # required
bot_token = "7090341693:AAHyw2Gj5lTWwj_U85s2MnNM6nm7ak7vZhs"                  # either bot_token or session_string is required
sudo_users = [6546273584]
# chat ids can be obtained from https://t.me/getidsbot
# All chats must be in the format of [-]1001234567890
# You can add multiple chats in the format of a list
# You can also add multiple chats in the format of a list of lists
# Atleast one chat must be added

[[chats]]
from = -1002212938036        # required
to = -1002156127206              # required



[[chats]]
from = -1002234510106        # required
to = -1002234510106             # required



[[chats]]
from = -1002212938036        # required
to = -1002215324637
